### ISSUE TITLE
Install via pypi

### ISSUE THREAD

**Issue by samuelkolb** [wannesm/PySDD#10]
Currently the installation instruction is to pip install from GitHub, `pip install pysdd` does not currently seem to work correctly for me. Can this be fixed or is there a reason behind this decision?

On Linux I get:

    Could not find a version that satisfies the requirement pysdd (from versions: )
    No matching distribution found for pysdd

**Comment by wannesm** [comment]
It is not intended behavior. For me `pip install pysdd` works as expected on Ubuntu 17.04. Can you give some more context? E.g. `pip --version`.

The version on the PyPI repository is indeed also kept up-to-date nowadays, so I updated the readme.

**Comment by wannesm** [comment]
PySDD only supports Python 3. So if `pip` is linked to the Python 2 version it will say it cannot be found. Use `pip3`.
