### ISSUE TITLE
Pip installation

### ISSUE THREAD

**Issue by jjcmoon** [wannesm/PySDD#16]
After installing with `pip install pysdd` as instructed in the README, I couldn't run the example code:
```
>>> from pysdd.sdd import SddManager, Vtree, WmcManager
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pysdd.sdd'
```
However only importing pysdd worked.

I did get it to work by compiling from source and installing, but having to do this seems not ideal.

**Comment by wannesm** [comment]
Do you have more output from the pip command? Maybe try rerunning using `pip install -vvv --upgrade --force-reinstall --no-deps pysdd`.

**Comment by jjcmoon** [comment]
I investigated the issue, and think I found the cause in the pip logs: the compilation of `sdd.c` failed as I did not have the developer version of python:
```
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Ipysdd/lib/sdd-2.0/include -Ipysdd/src -Ipysdd/lib/sdd-2.0/src -Ipysdd/lib/sdd-2.0/src/fnf -fPIC -I/usr/local/lib/python3.6/dist-packages/cysignals -I/usr/include/python3.6m -c pysdd/sdd.c -o build/temp.linux-x86_64-3.6/pysdd/sdd.o -O3 -march=native -std=c99
    pysdd/sdd.c:28:10: fatal error: Python.h: No such file or directory
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
This was quickly resolved by:
```
sudo apt-get install libpython3-dev
```
After this i reinstalled via pip and everything worked fine.
It might be good to list `libpython3-dev` or `python3-dev` as a dependency.

**Comment by wannesm** [comment]
Thanks for the input. I've updated the readme file.
