### ISSUE TITLE
macOS - The clang compiler does not support '-march=native'

### ISSUE THREAD

**Issue by GabVenturato** [wannesm/PySDD#26]
When installing PySDD with `pip install pysdd` I receive the following error.

`clang: error: the clang compiler does not support '-march=native'`

[Here the full log](https://github.com/wannesm/PySDD/files/6657388/pysdd_vvv_march.txt) obtained running `pip install -vvv --upgrade --force-reinstall --no-deps --no-binary :all: pysdd`.

### Workaround?
After some investigation I've discovered that it can be solved with `export ARCHFLAGS="-arch x86_64"` before the installation. I don't know if this is just a workaround or if it can be considered an effective solution though.

### System Specification
- OS: macOS Big Sur 11.4
- Laptop: MacBook Pro (13-inch, 2020)
- Processor: i5-1038NG7
- `uname -p`: i386
- `uname -v`: Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64
- Python virtual environment with Python 3.8.2 and Cython 0.29.23, pip 21.1.2, setuptools 57.0.0

**Comment by mccharley** [comment]
Had same error while working on a different project. I found enabling backwards compatibility did the trick for me.

`export SYSTEM_VERSION_COMPAT=1`

Here's a [link](https://stackoverflow.com/a/65245427/8076929) to the article that helped.
