### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by epinar** [wannesm/PySDD#3]
After installing the SDD and replacing the pysdd/lib/sdd-2.0 and pysdd/lib/libsdd-2.0 , I try to build the pysdd but receive the error: 

pysdd/sdd.c:639:10: fatal error: 'io.h' file not found
#include "io.h"
         ^~~~~~
1 error generated.
error: command 'clang' failed with exit status 1

What might be the possible cause?

**Comment by wannesm** [comment]
You also need to place back the custom files that are in the pysdd repository (e.g. the io.h) file. On most platforms it is probably not necessary to replace the library files. Try compiling first from a clean repository without changing anything.
