### ISSUE TITLE
Problem with compiling dimacs file into sdd and vtree ?

### ISSUE THREAD

**Issue by LedaguenelArthur** [wannesm/PySDD#31]
Hi (again),

I am not sure this is a compilation problem, but I have been working with a toy problem represented by the following **ex1_dimacs.txt** file :
```
c This file was generated with the constraints_to_cnf module in this project.
c Starting from file 'ex1.sympy'.
c There are 5 variables present in the constraints, and 5 total variables, given by the shape [5].
c
p cnf 5 6
1 -2 0
1 -3 0
2 -4 0
2 -5 0
-2 -3 0
-4 -5 0
```

I have compiled this file using the standard command line prompt :
`pysdd -c ex1_dimacs.txt -W ex1.vtree -R ex1.sdd`

I have obtained the following **ex1.vtree** file :
```
c vtree number-of-nodes-in-vtree
c L id-of-leaf-vtree-node id-of-variable
c I id-of-internal-vtree-node id-of-left-child id-of-right-child
c
vtree 9
L 0 2
L 2 3
L 4 1
L 6 4
L 8 5
I 7 6 1516123455496
I 5 4 1516123455495
I 3 2 1516123455493
I 1 0 1516123455491
```

I am not sure this is a problem, but the "id-of-right-child" in the last four lines seem strange to me, it this normal that they are this high ?
(I have had problem processing this Vtree later that's why I believe it might be erronous)

Best regards,

**Comment by wannesm** [comment]
What platform and version are you using?

This looks like a C datatype misalignment issue. When running it on my computer I see the right result. But when looking at these oddly large numbers, the correct values are in there. For example, 1516123455491 is in binary 0b10110000100000000000000000000000000000011 while it should only be the last few bits which correctly represent 3 (thus 0b11). And this is the same for all large numbers.

**Comment by LedaguenelArthur** [comment]
Thanks a lot for that quick answer @wannesm !

I am not sure what you mean by the platform but I am using VS Code on a Windows 10 Pro x64 bits computer. The PySDD version installed is 0.2.11 (which I installed using `pip install git+https://github.com/wannesm/PySDD.git` I believe).

Is there anything I can do to correct this datatype misalignment issue ?

Best regards,
Arthur

**Comment by wannesm** [comment]
Either the C library (libsdd) or the Cython C code is compiled for 32bit on Windows (even thought it is a 64bit OS). We have to search where we would need to add an additional flag. In case you are interested the full compilation pipeline is available here (in the deploy branch): https://github.com/wannesm/PySDD/actions/runs/4719395649/jobs/8370161354

**Comment by LedaguenelArthur** [comment]
I must say I am not an expert in C or compatibility issues with an OS, so I am not sure how to procede from there... 😢
But thanks a lot I have a better idea of where the problem is now !

**Comment by LedaguenelArthur** [comment]
Hi @wannesm,

I used a WSL2 instance to bypass the issue and it seems to be working well ! I still don't know how to make it properly work on my Windows 10 Pro though...

Thanks a lot for your help !

**Comment by wannesm** [comment]
This problem is now also resolved for Windows in the current version available in master and on pypi.
